# Build context is kept small by .dockerignore.
#
# Dependencies are installed from a hash-pinned export of uv.lock, generated by
# scripts/build-service.sh in the ecosystem root. A bare `pip install <src>`
# resolves versions from PyPI at build time, which is how running images drifted
# past their own lockfile (measured: 15 of 23 packages on kryten-moderator).
FROM python:3.11

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && useradd --system --create-home --uid 1001 kryten

COPY pyproject.toml uv.lock README.md LICENSE requirements.lock.txt /tmp/kryten-robot/
COPY kryten /tmp/kryten-robot/kryten

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --require-hashes -r /tmp/kryten-robot/requirements.lock.txt \
    && pip install --no-cache-dir --no-deps /tmp/kryten-robot

# Fail the build rather than the deploy if the entry point is broken.
RUN python -c "import kryten; print('kryten', getattr(kryten, '__version__', '?'))"

RUN mkdir -p /etc/kryten/kryten-robot /var/lib/kryten/kryten-robot \
    && chown -R kryten:kryten /etc/kryten /var/lib/kryten

USER kryten

ENTRYPOINT ["python", "-m", "kryten"]
CMD ["--config", "/etc/kryten/kryten-robot/config.json"]
